resources:
- name: resource-android-demo
  type: git
  source:
    uri: git@github.com:mainephd/android-concourse-demo.git
    branch: master
    private_key: {{github-public-private-key}}

jobs:
- name: job-android-demo
  plan:
  - get: resource-android-demo
    trigger: true
  - task: build
    config:
      platform: linux
      image_resource:
          type: docker-image
          source: {repository: gfx2015/android}
      inputs:
      - name: resource-android-demo
      run:
        path: resource-bluetooth-scanner-android/gradlew
        args:
        - 'clean'
        - 'check'
        - 'assembleDebug'
        - '-PdisablePreDex'
        - '--info'
        - '--stacktrace'